// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Stackific Inc.

package main

// server.go owns the bare-`stax` local HTTP server. The server is
// loopback-only (serverListenAddr is 127.0.0.1:7829) so it never
// accepts connections from elsewhere on the network — this is a per-
// user CLI assistant, not a shared service. The handlers below speak
// the small JSON API that ships with stax today:
//
//   GET /api/hello   — liveness / capability probe; returns the running
//                      stax version so a UI can confirm the binary it's
//                      talking to.
//   GET /api/systems — reads .stax/_data_systems.yaml from the current
//                      working directory and returns its parsed
//                      systems registry as a JSON array. Missing file
//                      or missing project marker → 200 with an empty
//                      array (no project in cwd is a normal state, not
//                      an error worth a non-2xx).
//
// The handler / mux / lifecycle split makes the routes unit-testable
// via httptest.NewRecorder while runServer owns the listen-loop +
// signal-handling shell that is only meaningful in the real CLI.

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"path"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"syscall"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/text"
	"github.com/yuin/goldmark/util"
)

// embeddedFrontend is the static build output of the Vite SPA that
// ships in-binary as the Stax web UI. The `all:` prefix is required so
// dotfiles (e.g. asset hashes prefixed with `.`) survive the embed
// walk. The dist tree is regenerated by `task frontend-build` (or
// `cd frontend && npm run build`); it must exist on disk before
// `go build` runs or the embed directive fails at compile time.
//
//go:embed all:frontend/dist
var embeddedFrontend embed.FS

// frontendFS strips the leading "frontend/dist/" prefix so the
// http.FileServer treats the embed root as the web root — a request
// for `/index.html` reads `frontend/dist/index.html`. Computed once at
// init so the strip is shared by every request.
var frontendFS = mustSubFS(embeddedFrontend, "frontend/dist")

// mustSubFS panics on a misconfigured embed prefix (a configuration
// bug, not a runtime input), keeping init free of error returns the
// callers couldn't usefully recover from.
func mustSubFS(parent embed.FS, dir string) fs.FS {
	sub, err := fs.Sub(parent, dir)
	if err != nil {
		panic(fmt.Errorf("embed sub %q: %w", dir, err))
	}
	return sub
}

// systemEntry is the JSON shape for one row in the /api/systems
// response. id / name come straight from _data_systems.yaml's entries
// (parseRegistry's byID map carries the same pairs).
type systemEntry struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// helloResponse is the JSON shape for /api/hello. version pinned to the
// linker-injected Version constant so a UI knows which binary it's
// hitting without having to invoke `stax --version` separately.
type helloResponse struct {
	Message string `json:"message"`
	Version string `json:"version"`
}

// systemsResponse wraps the array in an object so the response can grow
// (pagination cursors, schema metadata) without becoming a breaking
// change to clients that already deserialize the response as a JSON
// object.
type systemsResponse struct {
	Systems []systemEntry `json:"systems"`
}

// planDetail is one matching plan in the /api/systems?id=<slug> response:
// just the frontmatter fields the UI needs to render the row (title,
// status badge, created date for relative-time formatting). The plan
// body is intentionally not included — /api/scope?id=<slug> serves the
// full markdown body for any plan a user actually opens.
type planDetail struct {
	Slug    string `json:"slug"`
	Title   string `json:"title"`
	Status  string `json:"status"`
	Created string `json:"created"`
}

// systemDetailResponse is the body of /api/systems?id=<slug> on a hit:
// the system's id and display name plus every plan whose frontmatter
// `systems:` array contains the id, sorted by filename slug (which is
// chronological because the prefix is zero-padded sequential).
type systemDetailResponse struct {
	ID    string       `json:"id"`
	Name  string       `json:"name"`
	Plans []planDetail `json:"plans"`
}

// apiErrorResponse is the body emitted for non-2xx JSON responses. Kept
// minimal so a UI can pattern-match the `error` field directly.
type apiErrorResponse struct {
	Error string `json:"error"`
}

// scopeListItem is one row in the /api/scopes response. Carries the
// fields the /scopes list view needs to render each card: slug
// (deep-link target for /scope?id=...), title, status (rendered as a
// chip), created (ISO 8601 UTC string the UI formats client-side), and
// the kebab-case ids of every system the plan declares (each rendered
// as a link to /system?id=...). The full markdown body is intentionally
// NOT surfaced — that's the /api/scope?id=<slug> detail endpoint's
// responsibility, and embedding it in every list row would inflate the
// payload before the user opens any one plan.
type scopeListItem struct {
	Slug    string   `json:"slug"`
	Title   string   `json:"title"`
	Status  string   `json:"status"`
	Created string   `json:"created"`
	Systems []string `json:"systems"`
}

// scopesListResponse wraps the array in an object so the response can
// grow (pagination, schema metadata) without becoming a breaking change
// to clients that already deserialize the body as a JSON object. Same
// shape rationale as systemsResponse.
type scopesListResponse struct {
	Scopes []scopeListItem `json:"scopes"`
}

// scopeDetail is the /api/scope?id=<slug> body: every frontmatter field
// the detail view needs plus the markdown body pre-rendered to HTML
// server-side (so the browser doesn't need its own markdown library).
// systems carries the kebab-case ids exactly as parsed from
// frontmatter, so the UI can compose /system?id=<id> links without
// having to re-parse anything.
type scopeDetail struct {
	Slug    string   `json:"slug"`
	Title   string   `json:"title"`
	Status  string   `json:"status"`
	Created string   `json:"created"`
	Systems []string `json:"systems"`
	HTML    string   `json:"html"`
}

// forceH6Headings is a goldmark AST transformer that pins every
// rendered markdown heading to <h6>. Plans contain `## Goal`,
// `## Approach`, `## Tasks` section headers and the surrounding page
// chrome (chip, breadcrumb, page title) already supplies the visual
// hierarchy — rendering plan headings as raw <h2> would dominate the
// detail page. Pinning to <h6> keeps the heading anchor (auto-id) and
// semantic outline behavior intact while letting CSS style them as
// quiet subheads.
//
// The transformer runs as an AST pass rather than a custom renderer
// override because mutating `*ast.Heading.Level` keeps every other
// goldmark feature (auto-ids, GFM extensions, escape behavior) on the
// default path — no need to reimplement HTML output.
type forceH6Headings struct{}

// Transform satisfies parser.ASTTransformer. Walk every node; when one
// is a heading, rewrite its level to 6.
func (forceH6Headings) Transform(doc *ast.Document, _ text.Reader, _ parser.Context) {
	_ = ast.Walk(doc, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}
		if h, ok := n.(*ast.Heading); ok {
			h.Level = 6
		}
		return ast.WalkContinue, nil
	})
}

// markdownRenderer is the shared goldmark instance used to render plan
// bodies into HTML. Built once at package scope because the renderer is
// safe for concurrent use and constructing one per request would burn
// cycles for no benefit. GFM is enabled so plan tasks render as
// checkbox-styled list items; raw HTML in the markdown is escaped (no
// WithUnsafe) because plan files come from a user-editable tree. The
// forceH6Headings transformer pins every heading level to <h6> so plan
// section headers don't overwhelm the surrounding page chrome.
var markdownRenderer = goldmark.New(
	goldmark.WithExtensions(extension.GFM),
	goldmark.WithParserOptions(
		parser.WithAutoHeadingID(),
		parser.WithASTTransformers(util.Prioritized(forceH6Headings{}, 999)),
	),
)

// newServerMux builds the ServeMux that runServer (and the unit tests)
// register handlers against. Extracted from runServer so handler
// behavior can be exercised with httptest.NewServer / NewRecorder
// without spinning the listen loop or the signal-handling shell.
//
// Route precedence: ServeMux matches longest pattern first, so the
// explicit `/api/*` registrations take priority over the catch-all `/`
// static handler — a request for `/api/hello` lands on the JSON
// handler, not the embedded SPA. Everything else flows through
// handleFrontend, which adds clean-URL behavior on top of the raw
// file server (see that function's doc).
func newServerMux() *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc(apiHelloPath, handleAPIHello)
	mux.HandleFunc(apiSystemsPath, handleAPISystems)
	mux.HandleFunc(apiScopesPath, handleAPIScopes)
	mux.HandleFunc(apiScopePath, handleAPIScope)
	mux.HandleFunc("/", handleFrontend)
	return mux
}

// frontendFileServer is the raw embedded-FS file server reused by every
// hit handleFrontend forwards. Built once at package scope so each
// request pays only a method dispatch, not a fresh constructor.
var frontendFileServer = http.FileServer(http.FS(frontendFS))

// handleFrontend serves the embedded Vite SPA from frontendFS with the
// two niceties the multi-page output needs that net/http's bare
// FileServer doesn't provide:
//
//   - clean URLs: a request for `/systems` falls back to `systems.html`
//     when the exact path doesn't exist. The dist tree ships flat
//     `*.html` files at the root (systems.html, search.html, …), not
//     `<page>/index.html` subdirectories, so without this fallback
//     every page except `/` would 404.
//   - 404.html fallback: when neither the exact path nor the `.html`
//     variant exists, return the SPA's branded 404 page with a 404
//     status — same look as the rest of the UI.
//
// Path normalization is intentionally minimal: leading `/` is
// stripped, and the candidate is checked via fs.Stat against the
// embed. embed.FS doesn't honor `..` segments, so traversal attempts
// resolve to non-existent names and harmlessly fall through to the
// 404 branch.
func handleFrontend(w http.ResponseWriter, r *http.Request) {
	p := strings.TrimPrefix(r.URL.Path, "/")
	// Root path: let the file server resolve "" → "index.html".
	if p == "" {
		frontendFileServer.ServeHTTP(w, r)
		return
	}
	// Exact-file match (the common case for `/bundle.js`, asset files,
	// `/index.html` if requested explicitly).
	if info, err := fs.Stat(frontendFS, p); err == nil && !info.IsDir() {
		frontendFileServer.ServeHTTP(w, r)
		return
	}
	// Clean-URL fallback: extension-less paths get `.html` appended
	// when the resulting file exists. Cloning the request so the
	// upstream file server sees the rewritten URL without mutating the
	// shared request object the test harness inspects.
	if path.Ext(p) == "" {
		if _, err := fs.Stat(frontendFS, p+".html"); err == nil {
			r2 := r.Clone(r.Context())
			r2.URL.Path = r.URL.Path + ".html"
			frontendFileServer.ServeHTTP(w, r2)
			return
		}
	}
	// 404.html fallback (branded), if the embed ships one.
	if data, err := fs.ReadFile(frontendFS, "404.html"); err == nil {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusNotFound)
		_, _ = w.Write(data)
		return
	}
	// Last-resort generic 404.
	http.NotFound(w, r)
}

// handleAPIHello is the simplest endpoint: a JSON `{message, version}`
// pair. No request-body inspection, no cwd-dependent state — purely a
// liveness probe a UI can use to confirm the server is up and which
// stax version it represents.
func handleAPIHello(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, helloResponse{
		Message: "hello",
		Version: Version,
	})
}

// handleAPISystems serves /api/systems in two modes:
//
//   - list mode (no `id` query): returns the parsed registry as JSON.
//     A missing registry file or a cwd that is not a stax project
//     produces a 200 with an empty array — "no systems yet" is a
//     normal state for the UI to render an empty panel against, not an
//     error to surface as a non-2xx.
//   - detail mode (`?id=<slug>`): returns the named system plus every
//     plan whose frontmatter `systems:` array contains the id, with
//     each plan's markdown body pre-rendered to HTML. An unknown id
//     produces a 404 with a JSON error so the UI can show a not-found
//     state instead of an empty list (which would be indistinguishable
//     from "system exists but has no plans yet").
//
// Both modes read from cwd, which is the de-facto project root for the
// running stax process (set via --cwd in runDefault or inherited from
// the shell).
func handleAPISystems(w http.ResponseWriter, r *http.Request) {
	id := r.URL.Query().Get("id")
	if id == "" {
		writeJSON(w, http.StatusOK, systemsResponse{
			Systems: readSystemsForAPI(filepath.Join(staxDir, staxSystemsFile)),
		})
		return
	}
	detail, ok := readSystemDetail(staxDir, id)
	if !ok {
		writeJSON(w, http.StatusNotFound, apiErrorResponse{Error: "system not found"})
		return
	}
	writeJSON(w, http.StatusOK, detail)
}

// readSystemDetail is the testable body of handleAPISystems' detail
// branch. Takes the project's stax directory and a system id; returns
// the populated response plus a found bool. A false found means the id
// is not declared in .stax/_data_systems.yaml — handleAPISystems
// translates that into a 404. plans is empty (not nil) when the id is
// known but no plan declares it, so the JSON encodes an explicit `[]`.
//
// Plan order is filename sort descending — newest plans first, because
// the numeric prefix is zero-padded sequential. Matches the default of
// `stax plans list` (which also emits desc) and gives the UI the most
// recent work above the fold.
func readSystemDetail(staxDir, id string) (systemDetailResponse, bool) {
	reg := parseRegistry(filepath.Join(staxDir, staxSystemsFile))
	name, known := reg.byID[id]
	if !known {
		return systemDetailResponse{}, false
	}

	files, _ := filepath.Glob(filepath.Join(staxDir, "*"+planFileExt))
	sort.Sort(sort.Reverse(sort.StringSlice(files)))

	plans := make([]planDetail, 0, len(files))
	for _, f := range files {
		detail, ok := readPlanForAPI(f, id)
		if !ok {
			continue
		}
		plans = append(plans, detail)
	}
	return systemDetailResponse{ID: id, Name: name, Plans: plans}, true
}

// readPlanForAPI reads one plan file and, if its frontmatter declares
// the supplied id in its `systems:` array, returns the planDetail row.
// Returns (_, false) for files that fail to parse or lack the id —
// individual bad plans never abort the whole /api/systems?id=... call.
func readPlanForAPI(planPath, id string) (planDetail, bool) {
	row, ok := parsePlan(planPath, io.Discard)
	if !ok || !slices.Contains(row.systems, id) {
		return planDetail{}, false
	}
	title, created := readPlanTitleAndCreated(planPath)
	return planDetail{
		Slug:    row.slug,
		Title:   title,
		Status:  row.status,
		Created: created,
	}, true
}

// readPlanTitleAndCreated extracts the `title:` and `created:`
// frontmatter values from a plan file. Missing or unreadable files
// yield empty strings — the caller has already validated through
// parsePlan that the file is structurally sound, so this is purely an
// optional-fields read. Frontmatter parsing duplicates the open/close
// fence walk from parsePlan because parsePlan does not surface these
// two fields.
func readPlanTitleAndCreated(planPath string) (title, created string) {
	data, err := os.ReadFile(planPath) // #nosec G304,G703 -- planPath comes from filepath.Glob on staxDir.
	if err != nil {
		return "", ""
	}
	content := string(data)
	if !strings.HasPrefix(content, "---\n") && !strings.HasPrefix(content, "---\r\n") {
		return "", ""
	}
	end := strings.Index(content[3:], "\n---")
	if end < 0 {
		return "", ""
	}
	fm := content[3 : 3+end]
	if m := planTitleRe.FindStringSubmatch(fm); m != nil {
		title = strings.Trim(strings.TrimSpace(m[1]), `"'`)
	}
	if m := planCreatedRe.FindStringSubmatch(fm); m != nil {
		created = strings.TrimSpace(m[1])
	}
	return title, created
}

// handleAPIScopes serves /api/scopes — the list view that backs the
// /scopes web page. Returns one row per plan file in cwd's .stax/
// directory, carrying the slug (deep-link target), the title, and the
// kebab-case ids of every system the plan declares (rendered by the
// UI as links into /system?id=<id>). Missing .stax/ or a cwd that is
// not a stax project produce a 200 with an empty array, matching the
// "empty state is not an error" contract /api/systems uses.
//
// Plans whose frontmatter is malformed (missing status, missing
// systems, no closing fence) are skipped silently — parsePlan logs to
// io.Discard here so a broken plan never aborts the whole list. The
// `stax plans lint` subcommand is the user-facing way to surface those
// per-file findings.
func handleAPIScopes(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, scopesListResponse{
		Scopes: readScopesForAPI(staxDir),
	})
}

// handleAPIScope serves /api/scope?id=<slug> — the detail view that
// backs the /scope?id=<slug> web page. Returns the full plan body
// pre-rendered to HTML plus every frontmatter field the detail UI
// needs. Missing or unparseable plan files produce a 404 with a
// `{error}` body so the UI can show a not-found state.
func handleAPIScope(w http.ResponseWriter, r *http.Request) {
	id := r.URL.Query().Get("id")
	if id == "" {
		writeJSON(w, http.StatusBadRequest, apiErrorResponse{Error: "missing required query parameter: id"})
		return
	}
	detail, ok := readScopeDetail(staxDir, id)
	if !ok {
		writeJSON(w, http.StatusNotFound, apiErrorResponse{Error: "scope not found"})
		return
	}
	writeJSON(w, http.StatusOK, detail)
}

// readScopesForAPI is the testable body of handleAPIScopes: walks
// staxDir for plan files and returns one row per parseable plan,
// sorted by slug (which equals filename order because the prefix is
// zero-padded sequential). Missing staxDir returns an empty slice so
// the UI's empty state surfaces naturally.
func readScopesForAPI(staxDir string) []scopeListItem {
	files, _ := filepath.Glob(filepath.Join(staxDir, "*"+planFileExt))
	sort.Sort(sort.Reverse(sort.StringSlice(files)))
	out := make([]scopeListItem, 0, len(files))
	for _, f := range files {
		row, ok := parsePlan(f, io.Discard)
		if !ok {
			continue
		}
		title, created := readPlanTitleAndCreated(f)
		out = append(out, scopeListItem{
			Slug:    row.slug,
			Title:   title,
			Status:  row.status,
			Created: created,
			Systems: append([]string(nil), row.systems...),
		})
	}
	return out
}

// readScopeDetail is the testable body of handleAPIScope: reads one
// plan file by slug, returns the populated detail plus a found bool.
// false means the file doesn't exist, doesn't parse, or its body
// can't be rendered — callers translate that into a 404.
func readScopeDetail(staxDir, slug string) (scopeDetail, bool) {
	planPath := filepath.Join(staxDir, slug+planFileExt)
	row, ok := parsePlan(planPath, io.Discard)
	if !ok {
		return scopeDetail{}, false
	}
	body, ok := readPlanBody(planPath)
	if !ok {
		return scopeDetail{}, false
	}
	title, created := readPlanTitleAndCreated(planPath)
	var buf bytes.Buffer
	if err := markdownRenderer.Convert([]byte(body), &buf); err != nil {
		return scopeDetail{}, false
	}
	return scopeDetail{
		Slug:    row.slug,
		Title:   title,
		Status:  row.status,
		Created: created,
		Systems: append([]string(nil), row.systems...),
		HTML:    buf.String(),
	}, true
}

// readSystemsForAPI is the testable body of handleAPISystems: takes
// the registry-file path, returns a deterministically-sorted slice of
// systemEntry. Missing or unparseable files surface as an empty slice,
// matching the "200 with empty array" contract handleAPISystems
// guarantees to callers. Sorted by id so a UI can render a stable
// list without re-sorting client-side.
func readSystemsForAPI(registryPath string) []systemEntry {
	reg := parseRegistry(registryPath)
	out := make([]systemEntry, 0, len(reg.byID))
	for id, name := range reg.byID {
		out = append(out, systemEntry{ID: id, Name: name})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

// writeJSON marshals payload and writes it with the supplied status
// code and a `Content-Type: application/json` header. Centralized so
// every handler emits the same wire shape (header set BEFORE
// WriteHeader, encoder error swallowed because at-write-time there's
// nothing useful to do with an already-streamed-partial response).
func writeJSON(w http.ResponseWriter, status int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(payload)
}

// listenWithFallback is the production entry point — wires
// listenWithFallbackOn to the package-level serverListenAddr /
// serverDisplayURL / serverPortFallbackAttempts constants. Pulled
// apart from its parameterized form so tests can drive the fallback
// loop against arbitrary base ports (selected via 127.0.0.1:0 to
// avoid colliding with the user's running stax server on 7829).
func listenWithFallback(stderr io.Writer) (net.Listener, string, error) {
	displayHost, err := displayHostFromURL(serverDisplayURL)
	if err != nil {
		return nil, "", err
	}
	return listenWithFallbackOn(serverListenAddr, displayHost, serverPortFallbackAttempts, stderr)
}

// listenWithFallbackOn binds the preferred bindAddr first and, if it
// is already in use, walks forward through `attempts` adjacent ports
// (basePort+1, basePort+2, …) until it finds a free one. Returns the
// bound listener plus the user-facing URL composed from displayHost
// (typically `localhost`) and the actually-bound port.
//
// A successful fallback prints a single line to stderr explaining the
// port shift; otherwise the function is silent so the normal "listening
// on …" banner stays the first thing the user reads on stdout.
//
// Non-EADDRINUSE errors (permission denied, bad host, etc.) are
// returned immediately — those won't resolve by trying a different
// port, so retrying would just hide the real diagnostic.
func listenWithFallbackOn(bindAddr, displayHost string, attempts int, stderr io.Writer) (net.Listener, string, error) {
	bindHost, basePortStr, err := net.SplitHostPort(bindAddr)
	if err != nil {
		return nil, "", fmt.Errorf("parse bind addr %q: %w", bindAddr, err)
	}
	basePort, err := strconv.Atoi(basePortStr)
	if err != nil {
		return nil, "", fmt.Errorf("parse port from bind addr %q: %w", bindAddr, err)
	}
	var lastErr error
	for offset := 0; offset <= attempts; offset++ {
		port := basePort + offset
		addr := net.JoinHostPort(bindHost, strconv.Itoa(port))
		ln, lerr := net.Listen("tcp", addr)
		if lerr == nil {
			runtimeURL := "http://" + net.JoinHostPort(displayHost, strconv.Itoa(port))
			if offset > 0 {
				_, _ = fmt.Fprintf(stderr,
					"port %d already in use, using %d instead\n", basePort, port)
			}
			return ln, runtimeURL, nil
		}
		if !errors.Is(lerr, syscall.EADDRINUSE) {
			return nil, "", lerr
		}
		lastErr = lerr
	}
	return nil, "", fmt.Errorf("ports %d..%d all in use: %w",
		basePort, basePort+attempts, lastErr)
}

// displayHostFromURL extracts the host portion of serverDisplayURL so
// listenWithFallback can compose a runtime URL that keeps the same
// user-facing host (e.g. `localhost`) regardless of which port the
// listener ended up on. Pulled out so a malformed serverDisplayURL
// (a programming error) surfaces with a clear message rather than
// silently corrupting the banner.
func displayHostFromURL(raw string) (string, error) {
	u, err := url.Parse(raw)
	if err != nil {
		return "", fmt.Errorf("parse serverDisplayURL %q: %w", raw, err)
	}
	h := u.Hostname()
	if h == "" {
		return "", fmt.Errorf("serverDisplayURL %q has no host", raw)
	}
	return h, nil
}

// runServer starts the loopback HTTP server, optionally hands the URL
// to the OS-default browser, and blocks until the process receives
// SIGINT or SIGTERM (Ctrl-C in an interactive shell, kill in a script).
// Returns nil on a clean shutdown, non-nil on bind failure or an
// http.Server.Serve error other than http.ErrServerClosed.
//
// autoOpenBrowser gates the browser handoff: callers pass true on the
// default bare-stax path and false when `--no-browser` is set (or the
// host is headless, but the hasDesktop() check below also enforces
// that). The actual open is best-effort — a failure logs to stderr
// and the server keeps running so the URL print is still actionable.
func runServer(stdout, stderr io.Writer, autoOpenBrowser bool) error {
	mux := newServerMux()
	srv := &http.Server{
		Handler:           mux,
		ReadHeaderTimeout: serverReadHeaderTimeout,
	}

	// Bind explicitly via listenWithFallback so a port collision walks
	// forward through serverPortFallbackAttempts adjacent ports before
	// giving up. The runtime URL (which may differ from serverDisplayURL
	// when the preferred port was busy) is what every downstream caller
	// sees in the banner / browser handoff.
	ln, runtimeURL, err := listenWithFallback(stderr)
	if err != nil {
		return fmt.Errorf("listen near %s: %w", serverListenAddr, err)
	}

	// Announce on stdout so the user (or a wrapping script) can see
	// where to connect. Stdout (not stderr) so it pipes cleanly into
	// `stax | grep` patterns and so the line is the first thing in
	// the captured output of a CI smoke test.
	_, _ = fmt.Fprintf(stdout, "Stax server listening on %s\n", runtimeURL)
	_, _ = fmt.Fprintln(stdout, "  Press Ctrl-C to stop.")

	// Optional browser handoff. hasDesktop() suppresses the launch on
	// headless boxes (CI, SSH-into-server) so the server still runs
	// without spamming an error from a missing xdg-open. Errors during
	// the handoff are non-fatal — the URL is already printed.
	if autoOpenBrowser && hasDesktop() {
		if err := openBrowser(runtimeURL); err != nil {
			_, _ = fmt.Fprintf(stderr, "warning: could not open browser: %v\n", err)
		}
	}

	// Serve in a goroutine so the main goroutine can wait on either
	// the signal channel or a server failure, whichever comes first.
	serveErr := make(chan error, 1)
	go func() {
		err := srv.Serve(ln)
		if err == http.ErrServerClosed {
			err = nil
		}
		serveErr <- err
	}()

	// Standard graceful-shutdown shape: catch SIGINT/SIGTERM, give the
	// server a bounded window to drain in-flight requests, then return.
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
	defer signal.Stop(sigCh)

	select {
	case sig := <-sigCh:
		_, _ = fmt.Fprintf(stderr, "received %s, shutting down\n", sig)
		ctx, cancel := context.WithTimeout(context.Background(), serverShutdownTimeout)
		defer cancel()
		// Shutdown error is intentionally folded into the Serve error
		// channel: if Serve already returned (e.g. a hung handler), the
		// channel read below picks that up; otherwise Shutdown causes
		// Serve to return ErrServerClosed and our goroutine signals nil.
		_ = srv.Shutdown(ctx)
		return <-serveErr
	case err := <-serveErr:
		return err
	}
}
