// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Stackific Inc.

package main

// server.go owns the bare-`stax` local HTTP server. The server is
// loopback-only (serverListenAddr is 127.0.0.1:7829) so it never
// accepts connections from elsewhere on the network — this is a per-
// user CLI assistant, not a shared service. The handlers below speak
// the small JSON API that ships with stax today:
//
//   GET /api/hello   — liveness / capability probe; returns the running
//                      stax version so a UI can confirm the binary it's
//                      talking to.
//   GET /api/systems — reads .stax/_data_systems.yaml from the current
//                      working directory and returns its parsed
//                      systems registry as a JSON array. Missing file
//                      or missing project marker → 200 with an empty
//                      array (no project in cwd is a normal state, not
//                      an error worth a non-2xx).
//
// The handler / mux / lifecycle split makes the routes unit-testable
// via httptest.NewRecorder while runServer owns the listen-loop +
// signal-handling shell that is only meaningful in the real CLI.

import (
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
)

// embeddedFrontend is the static build output of the Vite SPA that
// ships in-binary as the Stax web UI. The `all:` prefix is required so
// dotfiles (e.g. asset hashes prefixed with `.`) survive the embed
// walk. The dist tree is regenerated by `task frontend-build` (or
// `cd frontend && npm run build`); it must exist on disk before
// `go build` runs or the embed directive fails at compile time.
//
//go:embed all:frontend/dist
var embeddedFrontend embed.FS

// frontendFS strips the leading "frontend/dist/" prefix so the
// http.FileServer treats the embed root as the web root — a request
// for `/index.html` reads `frontend/dist/index.html`. Computed once at
// init so the strip is shared by every request.
var frontendFS = mustSubFS(embeddedFrontend, "frontend/dist")

// mustSubFS panics on a misconfigured embed prefix (a configuration
// bug, not a runtime input), keeping init free of error returns the
// callers couldn't usefully recover from.
func mustSubFS(parent embed.FS, dir string) fs.FS {
	sub, err := fs.Sub(parent, dir)
	if err != nil {
		panic(fmt.Errorf("embed sub %q: %w", dir, err))
	}
	return sub
}

// systemEntry is the JSON shape for one row in the /api/systems
// response. id / name come straight from _data_systems.yaml's entries
// (parseRegistry's byID map carries the same pairs).
type systemEntry struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// helloResponse is the JSON shape for /api/hello. version pinned to the
// linker-injected Version constant so a UI knows which binary it's
// hitting without having to invoke `stax --version` separately.
type helloResponse struct {
	Message string `json:"message"`
	Version string `json:"version"`
}

// systemsResponse wraps the array in an object so the response can grow
// (pagination cursors, schema metadata) without becoming a breaking
// change to clients that already deserialize the response as a JSON
// object.
type systemsResponse struct {
	Systems []systemEntry `json:"systems"`
}

// newServerMux builds the ServeMux that runServer (and the unit tests)
// register handlers against. Extracted from runServer so handler
// behavior can be exercised with httptest.NewServer / NewRecorder
// without spinning the listen loop or the signal-handling shell.
//
// Route precedence: ServeMux matches longest pattern first, so the
// explicit `/api/*` registrations take priority over the catch-all `/`
// static handler — a request for `/api/hello` lands on the JSON
// handler, not the embedded SPA. Everything else flows through
// handleFrontend, which adds clean-URL behavior on top of the raw
// file server (see that function's doc).
func newServerMux() *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc(apiHelloPath, handleAPIHello)
	mux.HandleFunc(apiSystemsPath, handleAPISystems)
	mux.HandleFunc("/", handleFrontend)
	return mux
}

// frontendFileServer is the raw embedded-FS file server reused by every
// hit handleFrontend forwards. Built once at package scope so each
// request pays only a method dispatch, not a fresh constructor.
var frontendFileServer = http.FileServer(http.FS(frontendFS))

// handleFrontend serves the embedded Vite SPA from frontendFS with the
// two niceties the multi-page output needs that net/http's bare
// FileServer doesn't provide:
//
//   - clean URLs: a request for `/systems` falls back to `systems.html`
//     when the exact path doesn't exist. The dist tree ships flat
//     `*.html` files at the root (systems.html, search.html, …), not
//     `<page>/index.html` subdirectories, so without this fallback
//     every page except `/` would 404.
//   - 404.html fallback: when neither the exact path nor the `.html`
//     variant exists, return the SPA's branded 404 page with a 404
//     status — same look as the rest of the UI.
//
// Path normalization is intentionally minimal: leading `/` is
// stripped, and the candidate is checked via fs.Stat against the
// embed. embed.FS doesn't honor `..` segments, so traversal attempts
// resolve to non-existent names and harmlessly fall through to the
// 404 branch.
func handleFrontend(w http.ResponseWriter, r *http.Request) {
	p := strings.TrimPrefix(r.URL.Path, "/")
	// Root path: let the file server resolve "" → "index.html".
	if p == "" {
		frontendFileServer.ServeHTTP(w, r)
		return
	}
	// Exact-file match (the common case for `/bundle.js`, asset files,
	// `/index.html` if requested explicitly).
	if info, err := fs.Stat(frontendFS, p); err == nil && !info.IsDir() {
		frontendFileServer.ServeHTTP(w, r)
		return
	}
	// Clean-URL fallback: extension-less paths get `.html` appended
	// when the resulting file exists. Cloning the request so the
	// upstream file server sees the rewritten URL without mutating the
	// shared request object the test harness inspects.
	if path.Ext(p) == "" {
		if _, err := fs.Stat(frontendFS, p+".html"); err == nil {
			r2 := r.Clone(r.Context())
			r2.URL.Path = r.URL.Path + ".html"
			frontendFileServer.ServeHTTP(w, r2)
			return
		}
	}
	// 404.html fallback (branded), if the embed ships one.
	if data, err := fs.ReadFile(frontendFS, "404.html"); err == nil {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusNotFound)
		_, _ = w.Write(data)
		return
	}
	// Last-resort generic 404.
	http.NotFound(w, r)
}

// handleAPIHello is the simplest endpoint: a JSON `{message, version}`
// pair. No request-body inspection, no cwd-dependent state — purely a
// liveness probe a UI can use to confirm the server is up and which
// stax version it represents.
func handleAPIHello(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, helloResponse{
		Message: "hello",
		Version: Version,
	})
}

// handleAPISystems reads .stax/_data_systems.yaml from the current
// working directory and returns the parsed registry as JSON. cwd is
// the de-facto project root for the running stax process — set via
// --cwd before the server starts (in runDefault) or inherited from the
// shell. A missing file (or a cwd that simply isn't a stax project)
// produces a 200 with an empty array: from a UI's point of view, "no
// systems yet" is a valid state worth rendering an empty panel for,
// not an error to surface.
func handleAPISystems(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, systemsResponse{
		Systems: readSystemsForAPI(filepath.Join(staxDir, staxSystemsFile)),
	})
}

// readSystemsForAPI is the testable body of handleAPISystems: takes
// the registry-file path, returns a deterministically-sorted slice of
// systemEntry. Missing or unparseable files surface as an empty slice,
// matching the "200 with empty array" contract handleAPISystems
// guarantees to callers. Sorted by id so a UI can render a stable
// list without re-sorting client-side.
func readSystemsForAPI(registryPath string) []systemEntry {
	reg := parseRegistry(registryPath)
	out := make([]systemEntry, 0, len(reg.byID))
	for id, name := range reg.byID {
		out = append(out, systemEntry{ID: id, Name: name})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

// writeJSON marshals payload and writes it with the supplied status
// code and a `Content-Type: application/json` header. Centralized so
// every handler emits the same wire shape (header set BEFORE
// WriteHeader, encoder error swallowed because at-write-time there's
// nothing useful to do with an already-streamed-partial response).
func writeJSON(w http.ResponseWriter, status int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(payload)
}

// listenWithFallback is the production entry point — wires
// listenWithFallbackOn to the package-level serverListenAddr /
// serverDisplayURL / serverPortFallbackAttempts constants. Pulled
// apart from its parameterized form so tests can drive the fallback
// loop against arbitrary base ports (selected via 127.0.0.1:0 to
// avoid colliding with the user's running stax server on 7829).
func listenWithFallback(stderr io.Writer) (net.Listener, string, error) {
	displayHost, err := displayHostFromURL(serverDisplayURL)
	if err != nil {
		return nil, "", err
	}
	return listenWithFallbackOn(serverListenAddr, displayHost, serverPortFallbackAttempts, stderr)
}

// listenWithFallbackOn binds the preferred bindAddr first and, if it
// is already in use, walks forward through `attempts` adjacent ports
// (basePort+1, basePort+2, …) until it finds a free one. Returns the
// bound listener plus the user-facing URL composed from displayHost
// (typically `localhost`) and the actually-bound port.
//
// A successful fallback prints a single line to stderr explaining the
// port shift; otherwise the function is silent so the normal "listening
// on …" banner stays the first thing the user reads on stdout.
//
// Non-EADDRINUSE errors (permission denied, bad host, etc.) are
// returned immediately — those won't resolve by trying a different
// port, so retrying would just hide the real diagnostic.
func listenWithFallbackOn(bindAddr, displayHost string, attempts int, stderr io.Writer) (net.Listener, string, error) {
	bindHost, basePortStr, err := net.SplitHostPort(bindAddr)
	if err != nil {
		return nil, "", fmt.Errorf("parse bind addr %q: %w", bindAddr, err)
	}
	basePort, err := strconv.Atoi(basePortStr)
	if err != nil {
		return nil, "", fmt.Errorf("parse port from bind addr %q: %w", bindAddr, err)
	}
	var lastErr error
	for offset := 0; offset <= attempts; offset++ {
		port := basePort + offset
		addr := net.JoinHostPort(bindHost, strconv.Itoa(port))
		ln, lerr := net.Listen("tcp", addr)
		if lerr == nil {
			runtimeURL := "http://" + net.JoinHostPort(displayHost, strconv.Itoa(port))
			if offset > 0 {
				_, _ = fmt.Fprintf(stderr,
					"port %d already in use, using %d instead\n", basePort, port)
			}
			return ln, runtimeURL, nil
		}
		if !errors.Is(lerr, syscall.EADDRINUSE) {
			return nil, "", lerr
		}
		lastErr = lerr
	}
	return nil, "", fmt.Errorf("ports %d..%d all in use: %w",
		basePort, basePort+attempts, lastErr)
}

// displayHostFromURL extracts the host portion of serverDisplayURL so
// listenWithFallback can compose a runtime URL that keeps the same
// user-facing host (e.g. `localhost`) regardless of which port the
// listener ended up on. Pulled out so a malformed serverDisplayURL
// (a programming error) surfaces with a clear message rather than
// silently corrupting the banner.
func displayHostFromURL(raw string) (string, error) {
	u, err := url.Parse(raw)
	if err != nil {
		return "", fmt.Errorf("parse serverDisplayURL %q: %w", raw, err)
	}
	h := u.Hostname()
	if h == "" {
		return "", fmt.Errorf("serverDisplayURL %q has no host", raw)
	}
	return h, nil
}

// runServer starts the loopback HTTP server, optionally hands the URL
// to the OS-default browser, and blocks until the process receives
// SIGINT or SIGTERM (Ctrl-C in an interactive shell, kill in a script).
// Returns nil on a clean shutdown, non-nil on bind failure or an
// http.Server.Serve error other than http.ErrServerClosed.
//
// autoOpenBrowser gates the browser handoff: callers pass true on the
// default bare-stax path and false when `--no-browser` is set (or the
// host is headless, but the hasDesktop() check below also enforces
// that). The actual open is best-effort — a failure logs to stderr
// and the server keeps running so the URL print is still actionable.
func runServer(stdout, stderr io.Writer, autoOpenBrowser bool) error {
	mux := newServerMux()
	srv := &http.Server{
		Handler:           mux,
		ReadHeaderTimeout: serverReadHeaderTimeout,
	}

	// Bind explicitly via listenWithFallback so a port collision walks
	// forward through serverPortFallbackAttempts adjacent ports before
	// giving up. The runtime URL (which may differ from serverDisplayURL
	// when the preferred port was busy) is what every downstream caller
	// sees in the banner / browser handoff.
	ln, runtimeURL, err := listenWithFallback(stderr)
	if err != nil {
		return fmt.Errorf("listen near %s: %w", serverListenAddr, err)
	}

	// Announce on stdout so the user (or a wrapping script) can see
	// where to connect. Stdout (not stderr) so it pipes cleanly into
	// `stax | grep` patterns and so the line is the first thing in
	// the captured output of a CI smoke test.
	_, _ = fmt.Fprintf(stdout, "Stax server listening on %s\n", runtimeURL)
	_, _ = fmt.Fprintln(stdout, "  Press Ctrl-C to stop.")

	// Optional browser handoff. hasDesktop() suppresses the launch on
	// headless boxes (CI, SSH-into-server) so the server still runs
	// without spamming an error from a missing xdg-open. Errors during
	// the handoff are non-fatal — the URL is already printed.
	if autoOpenBrowser && hasDesktop() {
		if err := openBrowser(runtimeURL); err != nil {
			_, _ = fmt.Fprintf(stderr, "warning: could not open browser: %v\n", err)
		}
	}

	// Serve in a goroutine so the main goroutine can wait on either
	// the signal channel or a server failure, whichever comes first.
	serveErr := make(chan error, 1)
	go func() {
		err := srv.Serve(ln)
		if err == http.ErrServerClosed {
			err = nil
		}
		serveErr <- err
	}()

	// Standard graceful-shutdown shape: catch SIGINT/SIGTERM, give the
	// server a bounded window to drain in-flight requests, then return.
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
	defer signal.Stop(sigCh)

	select {
	case sig := <-sigCh:
		_, _ = fmt.Fprintf(stderr, "received %s, shutting down\n", sig)
		ctx, cancel := context.WithTimeout(context.Background(), serverShutdownTimeout)
		defer cancel()
		// Shutdown error is intentionally folded into the Serve error
		// channel: if Serve already returned (e.g. a hung handler), the
		// channel read below picks that up; otherwise Shutdown causes
		// Serve to return ErrServerClosed and our goroutine signals nil.
		_ = srv.Shutdown(ctx)
		return <-serveErr
	case err := <-serveErr:
		return err
	}
}
