// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Stackific Inc.

package main

// server.go owns the bare-`stax` local HTTP server. The server is
// loopback-only (serverListenAddr is 127.0.0.1:7829) so it never
// accepts connections from elsewhere on the network — this is a per-
// user CLI assistant, not a shared service. The handlers below speak
// the small JSON API that ships with stax today:
//
//   GET /api/hello   — liveness / capability probe; returns the running
//                      stax version so a UI can confirm the binary it's
//                      talking to.
//   GET /api/systems — reads .stax/_data_systems.yaml from the current
//                      working directory and returns its parsed
//                      systems registry as a JSON array. Missing file
//                      or missing project marker → 200 with an empty
//                      array (no project in cwd is a normal state, not
//                      an error worth a non-2xx).
//
// The handler / mux / lifecycle split makes the routes unit-testable
// via httptest.NewRecorder while runServer owns the listen-loop +
// signal-handling shell that is only meaningful in the real CLI.

import (
	"context"
	"embed"
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"net"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"sort"
	"syscall"
)

// embeddedFrontend is the static build output of the Vite SPA that
// ships in-binary as the Stax web UI. The `all:` prefix is required so
// dotfiles (e.g. asset hashes prefixed with `.`) survive the embed
// walk. The dist tree is regenerated by `task frontend-build` (or
// `cd frontend && npm run build`); it must exist on disk before
// `go build` runs or the embed directive fails at compile time.
//
//go:embed all:frontend/dist
var embeddedFrontend embed.FS

// frontendFS strips the leading "frontend/dist/" prefix so the
// http.FileServer treats the embed root as the web root — a request
// for `/index.html` reads `frontend/dist/index.html`. Computed once at
// init so the strip is shared by every request.
var frontendFS = mustSubFS(embeddedFrontend, "frontend/dist")

// mustSubFS panics on a misconfigured embed prefix (a configuration
// bug, not a runtime input), keeping init free of error returns the
// callers couldn't usefully recover from.
func mustSubFS(parent embed.FS, dir string) fs.FS {
	sub, err := fs.Sub(parent, dir)
	if err != nil {
		panic(fmt.Errorf("embed sub %q: %w", dir, err))
	}
	return sub
}

// systemEntry is the JSON shape for one row in the /api/systems
// response. id / name come straight from _data_systems.yaml's entries
// (parseRegistry's byID map carries the same pairs).
type systemEntry struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// helloResponse is the JSON shape for /api/hello. version pinned to the
// linker-injected Version constant so a UI knows which binary it's
// hitting without having to invoke `stax --version` separately.
type helloResponse struct {
	Message string `json:"message"`
	Version string `json:"version"`
}

// systemsResponse wraps the array in an object so the response can grow
// (pagination cursors, schema metadata) without becoming a breaking
// change to clients that already deserialize the response as a JSON
// object.
type systemsResponse struct {
	Systems []systemEntry `json:"systems"`
}

// newServerMux builds the ServeMux that runServer (and the unit tests)
// register handlers against. Extracted from runServer so handler
// behavior can be exercised with httptest.NewServer / NewRecorder
// without spinning the listen loop or the signal-handling shell.
//
// Route precedence: ServeMux matches longest pattern first, so the
// explicit `/api/*` registrations take priority over the catch-all `/`
// static handler — a request for `/api/hello` lands on the JSON
// handler, not the embedded SPA's index.html. Static files
// (`/index.html`, `/bundle.js`, every asset under `assets/`) flow
// through `http.FileServer(http.FS(frontendFS))`.
func newServerMux() *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc(apiHelloPath, handleAPIHello)
	mux.HandleFunc(apiSystemsPath, handleAPISystems)
	mux.Handle("/", http.FileServer(http.FS(frontendFS)))
	return mux
}

// handleAPIHello is the simplest endpoint: a JSON `{message, version}`
// pair. No request-body inspection, no cwd-dependent state — purely a
// liveness probe a UI can use to confirm the server is up and which
// stax version it represents.
func handleAPIHello(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, helloResponse{
		Message: "hello",
		Version: Version,
	})
}

// handleAPISystems reads .stax/_data_systems.yaml from the current
// working directory and returns the parsed registry as JSON. cwd is
// the de-facto project root for the running stax process — set via
// --cwd before the server starts (in runDefault) or inherited from the
// shell. A missing file (or a cwd that simply isn't a stax project)
// produces a 200 with an empty array: from a UI's point of view, "no
// systems yet" is a valid state worth rendering an empty panel for,
// not an error to surface.
func handleAPISystems(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, systemsResponse{
		Systems: readSystemsForAPI(filepath.Join(staxDir, staxSystemsFile)),
	})
}

// readSystemsForAPI is the testable body of handleAPISystems: takes
// the registry-file path, returns a deterministically-sorted slice of
// systemEntry. Missing or unparseable files surface as an empty slice,
// matching the "200 with empty array" contract handleAPISystems
// guarantees to callers. Sorted by id so a UI can render a stable
// list without re-sorting client-side.
func readSystemsForAPI(registryPath string) []systemEntry {
	reg := parseRegistry(registryPath)
	out := make([]systemEntry, 0, len(reg.byID))
	for id, name := range reg.byID {
		out = append(out, systemEntry{ID: id, Name: name})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

// writeJSON marshals payload and writes it with the supplied status
// code and a `Content-Type: application/json` header. Centralized so
// every handler emits the same wire shape (header set BEFORE
// WriteHeader, encoder error swallowed because at-write-time there's
// nothing useful to do with an already-streamed-partial response).
func writeJSON(w http.ResponseWriter, status int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(payload)
}

// runServer starts the loopback HTTP server, optionally hands the URL
// to the OS-default browser, and blocks until the process receives
// SIGINT or SIGTERM (Ctrl-C in an interactive shell, kill in a script).
// Returns nil on a clean shutdown, non-nil on bind failure or an
// http.Server.Serve error other than http.ErrServerClosed.
//
// autoOpenBrowser gates the browser handoff: callers pass true on the
// default bare-stax path and false when `--no-browser` is set (or the
// host is headless, but the hasDesktop() check below also enforces
// that). The actual open is best-effort — a failure logs to stderr
// and the server keeps running so the URL print is still actionable.
func runServer(stdout, stderr io.Writer, autoOpenBrowser bool) error {
	mux := newServerMux()
	srv := &http.Server{
		Handler:           mux,
		ReadHeaderTimeout: serverReadHeaderTimeout,
	}

	// Bind explicitly via net.Listen so a port collision surfaces as
	// an error returned to runDefault (which prints + exits non-zero)
	// rather than disappearing into a goroutine.
	ln, err := net.Listen("tcp", serverListenAddr)
	if err != nil {
		return fmt.Errorf("listen on %s: %w", serverListenAddr, err)
	}

	// Announce on stdout so the user (or a wrapping script) can see
	// where to connect. Stdout (not stderr) so it pipes cleanly into
	// `stax | grep` patterns and so the line is the first thing in
	// the captured output of a CI smoke test.
	_, _ = fmt.Fprintf(stdout, "Stax server listening on %s\n", serverDisplayURL)
	_, _ = fmt.Fprintln(stdout, "  Press Ctrl-C to stop.")

	// Optional browser handoff. hasDesktop() suppresses the launch on
	// headless boxes (CI, SSH-into-server) so the server still runs
	// without spamming an error from a missing xdg-open. Errors during
	// the handoff are non-fatal — the URL is already printed.
	if autoOpenBrowser && hasDesktop() {
		if err := openBrowser(serverDisplayURL); err != nil {
			_, _ = fmt.Fprintf(stderr, "warning: could not open browser: %v\n", err)
		}
	}

	// Serve in a goroutine so the main goroutine can wait on either
	// the signal channel or a server failure, whichever comes first.
	serveErr := make(chan error, 1)
	go func() {
		err := srv.Serve(ln)
		if err == http.ErrServerClosed {
			err = nil
		}
		serveErr <- err
	}()

	// Standard graceful-shutdown shape: catch SIGINT/SIGTERM, give the
	// server a bounded window to drain in-flight requests, then return.
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
	defer signal.Stop(sigCh)

	select {
	case sig := <-sigCh:
		_, _ = fmt.Fprintf(stderr, "received %s, shutting down\n", sig)
		ctx, cancel := context.WithTimeout(context.Background(), serverShutdownTimeout)
		defer cancel()
		// Shutdown error is intentionally folded into the Serve error
		// channel: if Serve already returned (e.g. a hung handler), the
		// channel read below picks that up; otherwise Shutdown causes
		// Serve to return ErrServerClosed and our goroutine signals nil.
		_ = srv.Shutdown(ctx)
		return <-serveErr
	case err := <-serveErr:
		return err
	}
}
